module BitwardenSDKSecrets
  class SecretsClient
    @command_runner: untyped

    @bitwarden_client: untyped

    def initialize: (untyped command_runner, untyped bitwarden_client) -> void

    def get: (untyped id) -> untyped

    def get_by_ids: (untyped ids) -> untyped

    def sync: (untyped last_synced_date) -> untyped

    def create: (untyped key, untyped value, untyped note, untyped project_ids) -> untyped

    def list: () -> untyped

    def update: (untyped id, untyped key, untyped value, untyped note, untyped project_ids) -> untyped

    def delete: (untyped ids) -> untyped

    private

    def error_response: (untyped response) -> (untyped | nil | untyped)

    def create_command: (untyped commands) -> untyped

    def run_command: (untyped command) -> untyped
  end
end
