/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BitwardenClient {
  constructor(settingsInput?: string | undefined | null, logLevel?: LogLevel | undefined | null);
  runCommand(commandInput: string): Promise<string>;
}

export declare const enum LogLevel {
  Trace = 0,
  Debug = 1,
  Info = 2,
  Warn = 3,
  Error = 4,
}
