name: Lint

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  security-events: write

jobs:
  style:
    name: Check Style

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install rust
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # stable
        with:
          toolchain: stable

      - name: Install rust nightly
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1

      - name: Cargo fmt
        run: cargo +nightly fmt --check

      - name: Install clippy-sarif and sarif-fmt
        run: cargo install clippy-sarif sarif-fmt --locked --git https://github.com/psastras/sarif-rs.git --rev 11c33a53f6ffeaed736856b86fb6b7b09fabdfd8

      - name: Cargo clippy
        run: cargo clippy --all-features --tests --message-format=json |
          clippy-sarif | tee clippy_result.sarif | sarif-fmt
        env:
          RUSTFLAGS: "-D warnings"

      - name: Upload Clippy results to GitHub
        uses: github/codeql-action/upload-sarif@42213152a85ae7569bdb6bec7bcd74cd691bfe41 # v3.30.9
        with:
          sarif_file: clippy_result.sarif
          sha: ${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.sha || github.sha }}
          ref: ${{ contains(github.event_name, 'pull_request') && format('refs/pull/{0}/head', github.event.pull_request.number) || github.ref }}

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          node-version: "16"

      - name: NPM setup
        run: npm ci

      - name: Node Lint
        run: npm run lint

      - name: Verify rust documentation links
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings"
