name: Release @bitwarden/sdk-wasm
run-name: Release @bitwarden/sdk-wasm ${{ inputs.release_type }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Options"
        required: true
        default: "Release"
        type: choice
        options:
          - Release
          - Dry Run

permissions: {}

jobs:
  trigger-deploy:
    name: Trigger Release in Deploy Repo
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
      id-token: write
    steps:
      - name: Trigger release via bitwarden/deploy
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: release-wasm
          data: |
            {
              "release_type": "${{ inputs.release_type }}"
            }
