name: Run all tests

on:
  pull_request:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-15
          - os: windows-2025
          - os: ubuntu-24.04

    runs-on: ${{ matrix.settings.os }}
    name: Run all tests - ${{ matrix.settings.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: ./scripts/bootstrap.sh all csharp
