name: Test Python Wheels

on:
  workflow_call:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    name: Test Python wheel - ${{ matrix.settings.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.settings.os || 'ubuntu-24.04' }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-15
            target: x86_64-apple-darwin

          - os: macos-15
            target: aarch64-apple-darwin

          - os: windows-2025
            target: x86_64-pc-windows-msvc

          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - os: ubuntu-24.04
            target: aarch64-unknown-linux-gnu

        # New Python versions are released in October:
        # https://devguide.python.org/versions/#supported-versions
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download wheel artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: bitwarden_sdk-*-${{ matrix.settings.target }}
          path: ${{ github.workspace }}/target/wheels
          merge-multiple: true

      - name: Start fake server
        run: |
          # Start the fake server in background for testing
          cargo run --bin fake-server &
          echo $! > fake_server.pid
          # Wait for server to start
          sleep 5
        working-directory: ${{ github.workspace }}

      - name: Run Python wheel tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          SM_FAKE_SERVER_PORT: 3000
        run: |
          ls -la ${{ github.workspace }}/target/wheels/ || echo "No wheels directory found"
          ./test_python.sh
        working-directory: ${{ github.workspace }}/crates/fake-server/scripts

      - name: Stop fake server
        if: always()
        run: |
          if [ -f fake_server.pid ]; then
            kill $(cat fake_server.pid) || true
            rm fake_server.pid
          fi
        working-directory: ${{ github.workspace }}
